server:
  port: 8089
spring:
  datasource:
    url: jdbc:mysql://117.72.16.114:3306/test_heima?useSSL=false
    username: root
    password: hikari
    driver-class-name: com.mysql.jdbc.Driver
logging:
  level:
    tracer: TRACE
    cn.itcast: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: cn.itcast.hotel.pojo